### HOME ROUTE
GET http://localhost:3000/


### GET ALL USERS
GET http://localhost:3000/users


### ABOUT ROUTE
GET http://localhost:3000/about


### CONTACT ROUTE
GET http://localhost:3000/contact


### REGISTER USER
POST http://localhost:3000/register
Content-Type: application/json

{
  "firstName": "Maurica",
  "lastName": "Bellaphant",
  "email": "maurica@gmail.com",
  "password": "password123"
}


### LOGIN USER
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "maurica@gmail.com",
  "password": "password123"
}


### DELETE USER
DELETE http://localhost:3000/users/imthebest